name = "webapp"
compatibility_date = "2025-10-24"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "webapp-production"
database_id = "local-dev-database"
